"""Add system_prompt to agents

Revision ID: 282a17b17210
Revises: ab2fefe2654f
Create Date: 2025-11-19 17:42:08.228084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282a17b17210'
down_revision = 'ab2fefe2654f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'system_prompt')
    # ### end Alembic commands ###

