"""Add input_data and output_data to executions

Revision ID: 43ab67adb82d
Revises: 282a17b17210
Create Date: 2025-11-19 17:55:28.827854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43ab67adb82d'
down_revision = '282a17b17210'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('executions', sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'output_data')
    op.drop_column('executions', 'input_data')
    # ### end Alembic commands ###

